using ApexGPTWinUI.Models;
using ApexGPTWinUI.Services;
using Microsoft.UI;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Windows.Media.SpeechRecognition;
using Windows.UI;

namespace ApexGPTWinUI
{
    // 1. UPDATED MODEL: Holds both Chat text AND Ticket Data
    public class UIMessage
    {
        // Type of message
        public bool IsTicket { get; set; } = false;

        // Standard Chat Data
        public string Text { get; set; } = string.Empty;
        public SolidColorBrush Color { get; set; } = new SolidColorBrush(Colors.LightGray);
        public SolidColorBrush ForeColor { get; set; } = new SolidColorBrush(Colors.Black);
        public HorizontalAlignment Alignment { get; set; } = HorizontalAlignment.Left;

        // Ticket Card Data
        public string TicketId { get; set; } = string.Empty;
        public string TicketStatus { get; set; } = string.Empty;
        public string TicketTitle { get; set; } = string.Empty;
        public string TicketPriority { get; set; } = string.Empty;
        public string TicketLogs { get; set; } = string.Empty; // For the report
        public SolidColorBrush StatusColor { get; set; } = new SolidColorBrush(Colors.Gray);
    }

    // 2. TEMPLATE SELECTOR: Decides whether to show a Bubble or a Card
    public class ChatTemplateSelector : DataTemplateSelector
    {
        public DataTemplate MessageTemplate { get; set; }
        public DataTemplate TicketTemplate { get; set; }

        protected override DataTemplate SelectTemplateCore(object item, DependencyObject container)
        {
            if (item is UIMessage msg && msg.IsTicket)
                return TicketTemplate;
            else
                return MessageTemplate;
        }
    }

    public sealed partial class MainWindow : Window
    {
        public ObservableCollection<UIMessage> Messages { get; set; } = new();
        private SafeTroubleshooter _troubleshooter = new SafeTroubleshooter();
        private static readonly HttpClient _httpClient = new HttpClient();
        private bool _isLiveEnvironment = true; // Set false for localhost

        public MainWindow()
        {
            this.InitializeComponent();
            ChatHistoryList.ItemsSource = Messages;
            AddBotMessage("System Online. Connected to ApexGPT Cloud Core.");
            InputAreaGrid.Visibility = Visibility.Visible;
        }

        // --- 1. SIDEBAR & NAVIGATION ---

        private void MenuButton_Click(object sender, RoutedEventArgs e) { }

        private void NewChatButton_Click(object sender, RoutedEventArgs e)
        {
            Messages.Clear();
            AddBotMessage("System Online. Connected to ApexGPT Cloud Core. New session started.");
            InputAreaGrid.Visibility = Visibility.Visible;
        }

        private async void HistoryButton_Click(object sender, RoutedEventArgs e)
        {
            const string userId = "user_0001";

            if (sender is Button btn) btn.IsEnabled = false;
            LoadingSpinner.Visibility = Visibility.Visible;
            InputAreaGrid.Visibility = Visibility.Collapsed;

            Messages.Clear();
            AddBotMessage($"Fetching ticket history for User {userId}...");

            await FetchTicketHistory(userId);

            LoadingSpinner.Visibility = Visibility.Collapsed;
            if (sender is Button finalBtn) finalBtn.IsEnabled = true;
        }

        // --- 2. REPORT GENERATION (New Feature) ---

        private void GenerateReport_Click(object sender, RoutedEventArgs e)
        {
            // Get the ticket data attached to the button
            if (sender is Button btn && btn.DataContext is UIMessage ticketMsg)
            {
                // Create a simulated report
                string report = $"📋 **OFFICIAL IT REPORT**\n" +
                                $"--------------------------------\n" +
                                $"TICKET: {ticketMsg.TicketId}\n" +
                                $"STATUS: {ticketMsg.TicketStatus.ToUpper()}\n" +
                                $"ISSUE: {ticketMsg.TicketTitle}\n" +
                                $"--------------------------------\n" +
                                $"LOGS & AUDIT TRAIL:\n" +
                                $"{ticketMsg.TicketLogs}\n" +
                                $"--------------------------------\n" +
                                $"Generated by ApexGPT Client at {DateTime.Now:HH:mm}";

                // Add the report to the chat stream
                Messages.Add(new UIMessage
                {
                    Text = report,
                    IsTicket = false,
                    Color = new SolidColorBrush(Color.FromArgb(255, 240, 248, 255)), // Light AliceBlue
                    ForeColor = new SolidColorBrush(Colors.Black),
                    Alignment = HorizontalAlignment.Stretch // Full width
                });

                // Scroll to bottom
                var scrollViewer = GetScrollViewer(ChatHistoryList);
                scrollViewer?.ChangeView(null, scrollViewer.ScrollableHeight, null);
            }
        }

        // Helper to scroll
        private ScrollViewer GetScrollViewer(DependencyObject depObj)
        {
            if (depObj is ScrollViewer) return depObj as ScrollViewer;
            for (int i = 0; i < VisualTreeHelper.GetChildrenCount(depObj); i++)
            {
                var child = VisualTreeHelper.GetChild(depObj, i);
                var result = GetScrollViewer(child);
                if (result != null) return result;
            }
            return null;
        }

        // --- 3. CORE CHAT LOGIC ---

        private void SendButton_Click(object sender, RoutedEventArgs e) => ProcessUserMessage();

        private void InputBox_KeyUp(object sender, Microsoft.UI.Xaml.Input.KeyRoutedEventArgs e)
        {
            if (e.Key == Windows.System.VirtualKey.Enter) ProcessUserMessage();
        }

        private async void ProcessUserMessage()
        {
            string text = InputBox.Text;
            if (string.IsNullOrWhiteSpace(text)) return;

            Messages.Add(new UIMessage
            {
                Text = text,
                Color = new SolidColorBrush(Microsoft.UI.Colors.RoyalBlue),
                ForeColor = new SolidColorBrush(Microsoft.UI.Colors.White),
                Alignment = HorizontalAlignment.Right
            });
            InputBox.Text = "";

            LoadingSpinner.Visibility = Visibility.Visible;
            SendButton.Visibility = Visibility.Collapsed;
            MicButton.Visibility = Visibility.Collapsed;

            await CallBotApi(text);

            LoadingSpinner.Visibility = Visibility.Collapsed;
            SendButton.Visibility = Visibility.Visible;
            MicButton.Visibility = Visibility.Visible;
        }

        private async Task CallBotApi(string userText)
        {
            try
            {
                var payload = new { Prompt = userText, UserId = "user_0001" };
                string json = JsonSerializer.Serialize(payload);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                string botUrl = _isLiveEnvironment ? "https://apexgpt-hackathon-bot-bxehhrc3ajcuanf5.westcentralus-01.azurewebsites.net/api/ai/ask" : "http://localhost:5142/api/ai/ask";

                HttpResponseMessage response = await _httpClient.PostAsync(botUrl, content);

                if (response.IsSuccessStatusCode)
                {
                    string responseString = await response.Content.ReadAsStringAsync();
                    using JsonDocument doc = JsonDocument.Parse(responseString);
                    string botReply = doc.RootElement.GetProperty("response").GetString() ?? "No Response";

                    if (botReply.Contains("COMMAND:"))
                        HandleCommand(botReply);
                    else
                        AddBotMessage(botReply);
                }
                else
                {
                    AddBotMessage($"Error: Server returned {response.StatusCode}");
                }
            }
            catch (Exception ex)
            {
                AddBotMessage($"Connection Failed: {ex.Message}");
            }
        }

        // --- 4. TICKET FETCHING (Updated for Cards) ---

        private async Task FetchTicketHistory(string userId)
        {
            try
            {
                string historyUrl = _isLiveEnvironment ? $"https://apexgpt-hackathon-bot-bxehhrc3ajcuanf5.westcentralus-01.azurewebsites.net/api/ai/history/{userId}" : $"http://localhost:5142/api/ai/history/{userId}";

                HttpResponseMessage response = await _httpClient.GetAsync(historyUrl);

                if (response.IsSuccessStatusCode)
                {
                    string responseString = await response.Content.ReadAsStringAsync();
                    var history = JsonSerializer.Deserialize<List<TicketHistoryItem>>(
                        responseString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                    if (history != null && history.Any())
                    {
                        Messages.Add(new UIMessage { Text = $"📂 Found {history.Count} tickets available for review:", Color = new SolidColorBrush(Colors.Transparent), Alignment = HorizontalAlignment.Center });

                        foreach (var ticket in history)
                        {
                            // Create a "Card" Message
                            Messages.Add(new UIMessage
                            {
                                IsTicket = true, // THIS TRIGGERS THE CARD UI
                                TicketId = ticket.Id,
                                TicketTitle = ticket.Title,
                                TicketStatus = ticket.Status,
                                TicketPriority = $"Priority {ticket.Priority}",
                                TicketLogs = string.Join("\n", ticket.TroubleshootingLogs),

                                // Color code the status
                                StatusColor = ticket.Status == "Resolved" ? new SolidColorBrush(Colors.SeaGreen) :
                                              ticket.Status == "Escalated" ? new SolidColorBrush(Colors.OrangeRed) :
                                              new SolidColorBrush(Colors.DodgerBlue),

                                Alignment = HorizontalAlignment.Stretch
                            });
                        }
                    }
                    else
                    {
                        AddBotMessage("No active or historical tickets found.");
                    }
                }
                else
                {
                    AddBotMessage($"Error fetching history: {response.StatusCode}");
                }
            }
            catch (Exception ex)
            {
                AddBotMessage($"Connection Error: {ex.Message}");
            }
        }

        // --- 5. HELPERS ---

        private void HandleCommand(string commandText)
        {
            string actionResult = "";
            string userMessage = "";
            string commandLower = commandText.ToLower();

            if (commandLower.Contains("check_disk")) userMessage = "Running disk hardware check...";
            else if (commandLower.Contains("check_ping")) userMessage = "Testing connectivity to 8.8.8.8...";
            else if (commandLower.Contains("flush_dns")) userMessage = "Flushing DNS cache...";
            else if (commandLower.Contains("reduce_ram")) userMessage = "Analyzing memory processes...";
            else if (commandLower.Contains("clean_disk")) userMessage = "Calculating cleanup size...";
            else if (commandLower.Contains("escalated")) userMessage = "ESCALATION ALERT:";

            actionResult = _troubleshooter.RunAction(commandLower.Replace("command:", "").Trim());

            AddBotMessage(userMessage);
            AddBotMessage($"RESULT:\n{actionResult}");
        }

        private void AddBotMessage(string text)
        {
            Messages.Add(new UIMessage
            {
                Text = text,
                Color = new SolidColorBrush(Color.FromArgb(255, 230, 230, 230)),
                ForeColor = new SolidColorBrush(Microsoft.UI.Colors.Black),
                Alignment = HorizontalAlignment.Left
            });
        }

        private async void MicButton_Click(object sender, RoutedEventArgs e)
        {
            MicButton.IsEnabled = false;
            InputBox.PlaceholderText = "Listening...";
            InputBox.Text = "";
            try
            {
                var speechRecognizer = new SpeechRecognizer();
                await speechRecognizer.CompileConstraintsAsync();
                SpeechRecognitionResult result = await speechRecognizer.RecognizeAsync();
                if (result.Status == SpeechRecognitionResultStatus.Success) InputBox.Text = result.Text;
            }
            catch { InputBox.PlaceholderText = "Mic Error"; }
            finally { MicButton.IsEnabled = true; if (string.IsNullOrEmpty(InputBox.Text)) InputBox.PlaceholderText = "Ask ApexGPT..."; }
        }
    }
}